version: '3'
services:
  app:
    build: .
    volumes:
      - ./ShrinkGPT.github.io:/ShrinkGPT.github.io
    working_dir: /ShrinkGPT.github.io
    command: bash -c "pip install --upgrade pip && pip install flask, flask_bootstrap && /bin/sh -c pip install --no-cache-dir -r requirements.txt && python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8080:8080
