text2speech:
  male: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_DAVID_11.0
  female: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0

auth:
  AUTH:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0
  STREAM:
    Content-Type: image/svg+xml